var app = document.getElementById('typewriter');
var typewriter = new Typewriter(app, {
    loop: false,
    delay: 31
});

typewriter.typeString('Dear Staci,')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('I hope you have a great birthday!')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
.typeString('This is a little rough but watch until the end (You can\'t tab out or it may break, so in one sitting!!)')
    .pauseFor(2400)
    .deleteAll()
.pauseFor(500)
    .typeString('I sometimes think about how life put us all in 21a together that Fall semester')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('It\'s one of the things where I wonder: \"What if it didn\'t happen?\"')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('But regardless, good thing it did :D')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('The best takeaways I\'ll have from college will be the memories, low and high, we made')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('You\'re smart, ambitious (among so many other things), but best of all an amazing friend')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('These past few years have helped me realize there\'s so many more dimensions to life')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('A big one is the people you surround yourself with')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('We have lighthearted laughs with our quirky humor but also the deepest convos')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('And most of all you showed me the epitome of friendship :D')
    .pauseFor(599)
    .deleteAll()
.pauseFor(500)
    .typeString('My only regret is that we had shared more of college together :(')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('I remember when we had just met, Lesbia and I asked you to join us to study with hot chocolate')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('And it was really cold, but you still came over to north')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('And then we had OS the next semester')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('Grinding in grad, drawing diagrams on a cracked whiteboard until 4am with tons of coffee')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('Then making protein pancakes the next day while I burned stuff in the pan')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('Meeting friends like Domingo, Mitchell, Adam, and Angeliki')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('And hunkering down in grad when the pandemic came, and all our zoom calls during lockdown')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('Then of course recently, Dallas, and so much more!')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('\"We didn\'t realize we were making memories, we were just having fun\" :(')
    .pauseFor(3000)
    .deleteAll()
    .pauseFor(900)
    .typeString('I really can\'t put it all into words, but you get the point!')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('But there are many years in the future for more memories.  I\'m super excited!')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('You flew in for my bday which was more than I could ever ask for, but I hope you enjoy this little thing for yours.  Thank you Staci :D')
    .pauseFor(599)
    .deleteAll()
    .pauseFor(500)
    .typeString('Anyways, enjoy the fireworks in a few moments!')
    .pauseFor(1000)
    .deleteAll()
    .pauseFor(4000)
    .typeString('Any second now...')
    .pauseFor(3500)
    .deleteAll()
    .pauseFor(3000)
    .typeString('Any second now...')
    .pauseFor(3500)
    .deleteAll()
    .pauseFor(3000)
    .typeString('Any second now...')
    .pauseFor(3500)
    .deleteAll()
    .start();

setTimeout(() => {
    document.getElementById("cover").style.display = "none"
 }, 157000);
